# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTcrSDn47Wc08gfRhoJR4uCj2KY-aH8b
"""

n = int(input("Enter a number: "))

f = []

for i in range(0, n):
  if i < 2:
    f.append(i)
  else:
    f.append(f[i-1] + f[i-2])

print(f)

print("the n-th position is " + str(f[n-1]))

n = int(input("Enter a number: "))

f = []

for i in range(n):
  if i < 2:
    f.append(i)
  else:
    f.append(f[i-1] + f[i-2])

print(f)

print("The n-th position is " + str(f[n-1]))